spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  batch:
    job:
      enabled: false
server:
  servlet:
    context-path: /api
custom:
  file-path: /app/files/
